--날짜형 함수
SELECT SYSDATE FROM DUAL; --24/07/01
SELECT ADD_MONTHS(SYSDATE, 1) FROM DUAL; --N개월 더함
SELECT MONTHS_BETWEEN(SYSDATE + 31 , SYSDATE) FROM DUAL; --두 날짜사이의 개월수 반환 
SELECT LAST_DAY(SYSDATE) FROM DUAL; --그 달의 마지막 일자를 반환

--형변환 함수
SELECT TO_NUMBER('123345') FROM DUAL; --CHAR를 숫자로 변환
SELECT TO_CHAR (12345, '99,999') FROM DUAL; --숫자 N을 NUMBER_FORMAT에 맞게 문자로 변환
SELECT TO_CHAR (SYSDATE, 'YYYY-MM-DD HH24:MI:SS')FROM DUAL; --날짜인 DATE를 DATE_FROMAT에 맞게 문자로 변환
SELECT TO_DATE ('2024-07-01 13:37:42', 'YYYY-MM-DD HH24:MI:SS')FROM DUAL; --문자 CHAR를 DATE_FORMAT에 맞게 날짜로 변환

--기타함수
--NULL관련 함수
SELECT NVL(NULL, 'N/A')
,NVL2('NULL인 경우 3 NULL이아닌경우 2',2,3)
,COALESCE(NULL,NULL,5,4,NULL) --첫번째로 NULL이 아닌경우 반환
,NULLIF('NULL','null') --두 값을 비교해 두값이 같으면 NULL을 같지 않으면 첫번째 값을 반환
FROM DUAL;

--CASE 단순형 표현식 => DECODE는 CASE와 같은 기능을함 단순형 CASE와 같음! 
SELECT AGE,
CASE AGE WHEN 33 THEN '33세' END AGES FROM EMP03; 

--CASE 검색형 표현식 *WHEN 절에서 조건식 사용 가능
SELECT 
AGE
,CASE WHEN age BETWEEN 20 AND 29 THEN '20대' 
      WHEN AGE BETWEEN 30 AND 39 THEN '3O대'
      WHEN AGE BETWEEN 40 AND 49 THEN '40대'
      WHEN AGE BETWEEN 50 AND 59 THEN '50대'
end ages
FROM EMP03;
